# MySQL Connection
db.url=jdbc:mysql://localhost:3306/contactbook
db.username=root
db.password=Harsha@16

# HikariCP Settings
pool.maximumPoolSize=10
pool.minimumIdle=2
pool.connectionTimeout=30000
pool.idleTimeout=600000
pool.maxLifetime=1800000